[package]
name = "first_lesson"
version = "0.1.0"
authors = ["nhatvu148 <54697578+nhatvu148@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
